build:
  version: 1.1

accounts:
  message: "This is Accounts Microservice"
  contactDetails:
    name: "Ayush Jaipuriar"
    email: "jaipuriar.ayush@gmail.com"
  onCallSupport:
    - "910909090"
    - "728782738"


