build:
  version: 1.0

accounts:
  message: "This is Accounts Microservice runing on QA profile"
  contactDetails:
    name: "Ayush Jaipuriar"
    email: "jaipuriar.ayush@gmail.com"
  onCallSupport:
    - "910909090"
    - "728782738"

spring:
  config:
    activate:
      on-profile: qa


