spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to loans related prod APIs "
  contactDetails:
    name: "Ayush Jaipuriar - Product Owner"
    email: "jaipuriar.ayush@gmail.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956