# Specifies the Docker Compose version used for defining the services and configuration.
version: '3.8'

# Defines the services (containers) that will be created.
services:

  # Service definition for the 'loans' microservice
  loans:
    # Specifies the Docker image to use for this service
    build: .
    # Assigns a custom name to the container for easier identification
    container_name: "loans-microservice"
    # Maps port 8090 on the host to port 8090 on the container
    ports:
      - "8090:8090"
    # Configures resource limits for the container
    deploy:
      resources:
        limits:
          # Sets the maximum memory usage for the container to 700 MB
          memory: 700M
    # Adds the 'loans' service to the custom-defined network
    networks:
      - microservices_network
    # Sets environment variables for the 'loans' microservice
    environment:
      - SPRING_APPLICATION_NAME=loans
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_CONFIG_IMPORT=configserver:http://localhost:8071
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_FETCH-REGISTRY=true
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:8070/eureka
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=true

# Network definition to allow communication between services
networks:
  # Custom network for connecting microservices together
  microservices_network:
    # Specifies the bridge network driver (isolates network traffic between services)
    driver: bridge
