build:
  version: "1.0"

loans:
  message: "Welcome to loans related production APIs "
  contactDetails:
    name: "Ayush Jaipuriar - Developer"
    email: "jaipuriar.ayush@gmail.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956