#Server configuration
server:
  port: 8080 #default port, but its a good practice to explicitly state it

#H2 Database configuration
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
        ddl-auto: update #Auto Creates the tables if not already created
    show-sql: true
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8071"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
  instance:
    prefer-ip-address: true

info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"

build:
  version: 1.1

accounts:
  message: "This is Accounts Microservice"
  contactDetails:
    name: "Ayush Jaipuriar"
    email: "jaipuriar.ayush@gmail.com"
  onCallSupport:
    - "910909090"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true

logging:
  level:
    com.drarc.accounts: DEBUG

feign:
  circuitbreaker:
    enabled: true

